### PR TITLE
update to support Terraform 0.7 plugin architecture

### PR DESCRIPTION
**Pull request by pdxfixit**
I'd like to contribute changes to make the plugin compatible with Terraform 0.7, but am not sure what the best practices are, for external plugins now.

Please feel free to argue for additional changes to be part of this PR.

### CODE REVIEW

**Comment by pdxfixit** [comment]
yeah.... Travis failed b/c it can't reference that import.  Grrr.

I'm open to ideas.

**Comment by pryorda** [comment]
@pdxfixit Looks like me need to change the travis-ci build scripts to do the actions you put in the readme?

**Comment by rbarkley** [comment]
Any progress on resolving this and releasing a 0.7+ compatible release?

**Comment by pdxfixit** [comment]
there are likely better ways to have done this; opinions welcome.

**Comment by pdxfixit** [comment]
@rbarkley the 0.6 release is now available

**Review by pryorda — COMMENTED** [review]
I havent been able to test this but it LGTM

**Pull request merged**
