### PR TITLE
add support to specify a snatpool

### PR DESCRIPTION
**Pull request by pdxfixit**
This change is dependent upon https://github.com/scottdware/go-bigip/pull/15.

Once that has been merged, tests should pass for this PR, and it can then be merged.

### CODE REVIEW

**Comment by aburnett** [comment]
Merged that PR. Still failing. https://travis-ci.org/DealerDotCom/terraform-provider-bigip/builds/160001292

**Comment by aburnett** [comment]
On a related note, are you interested in being added as a maintainer? I'm not in a position where I can maintain this any longer.

**Comment by pdxfixit** [comment]
Crap. I'll take a look in the morning.
Yeah, I'd be interested in helping to maintain the project. Thanks for
asking. :-)

**Comment by pryorda** [comment]
@pdxfixit Does the vendor files for go-bigip need updated?

**Comment by pdxfixit** [comment]
Yeah, that's exactly it. :) Fun stuff, learning golang. :)

**Comment by pryorda** [comment]
Learning go's use of weird stuffs that other languages have weird tools for :+1:

**Pull request merged**
