### PR TITLE
Adding Import Functionality

### PR DESCRIPTION
**Pull request by pdxfixit**
After reverting #33, I've moved the WIP to this PR.

### CODE REVIEW

**Comment by pdxfixit** [comment]
Current error is: https://travis-ci.org/DealerDotCom/terraform-provider-bigip/builds/175918073#L321-L327

**Comment by pryorda** [comment]
@pdxfixit thank you for reverting this. I didnt mean to merge it.

**Comment by pryorda** [comment]
We have to update the shema dependency.. I'm trying to get it right

**Comment by pryorda** [comment]
@pdxfixit Do you idle in irc anywhere? It would be nice if we could get this learning and it would be a learning experience for me :+1:

**Comment by pdxfixit** [comment]
Not IRC, but there are some other options which I do use.... I sent you an
email, let's connect there first.

**Comment by pryorda** [comment]
Waiting for a it to come through. Looks like github email relay is sloooow.

**Comment by pdxfixit** [comment]
First one was yesterday, fwiw. Might check spam folder.

**Comment by devinsba** [comment]
If I create a gitter.im room for this would that work for you two?

**Comment by pdxfixit** [comment]
Sure. And hello. :)

**Pull request merged**
