### PR TITLE
adding option for VLANs

### PR DESCRIPTION
**Pull request by st33v**

### CODE REVIEW

**Comment by pryorda** [comment]
@st33v  The code looks good, but i think we should add a test for this. @pdxfixit @aburnett Do you guys agree?

**Comment by aburnett** [comment]
Always ;)

**Comment by gliptak** [comment]
The last commit added a test to this PR.

**Comment by pdxfixit** [comment]
it would be nice to see the readme get updated also

**Comment by pdxfixit** [comment]
also, thanks @gliptak for writing the test

**Comment by gliptak** [comment]
@pdxfixit The PR was by @st33v

**Comment by gliptak** [comment]
I will submit a PR to update README.

PS Is there an "automagic" way to use the source files to generate the API description?

**Comment by pdxfixit** [comment]
I suspect there is, but I don't know of one.

**Comment by gliptak** [comment]
@pdxfixit I found this documentation generator https://github.com/segmentio/terraform-docs

**Pull request merged**
