### PR TITLE
Adding Import Functionality

### PR DESCRIPTION
**Pull request by pryorda**
I have functions for the import functionality complete. The issue I'm running into now is I dont know how to get govendor to pull in v7.0 of the terraform resources. Any tips you can throw my way will be beneficial.

Thanks

### CODE REVIEW

**Comment by aburnett** [comment]
@pdxfixit - Weren't you going down the same road w/ updating to 0.7? Can you lend a hand?

@pryorda - Any interest in helping take over as maintainer of this repo?

**Comment by pryorda** [comment]
Adam, I def am interested. Yes, but for somereason my govendor command fu is not working.
On Sep 14, 2016 6:55 PM, Adam Burnett notifications@github.com wrote:@pdxfixit - Weren't you going down the same road w/ updating to 0.7? Can you lend a hand?

@pryorda - Any interest in helping take over as maintainer of this repo?

**Comment by aburnett** [comment]
Ok you should have a collaborator invite in your notifications.

**Comment by pdxfixit** [comment]
I suggest doing the following;
(the govendor command must be run within context of the project)

```
go get -u all
govendor update foo
```

**Comment by pryorda** [comment]
@pdxfixit If the build is a success please review my changes to the vendors. I removed some stuff that appeared to be cruft.

**Comment by pdxfixit** [comment]
Hey, @pryorda, that build failed.  I'd like to revert the merge, until it passes.

I was looking into why it failed earlier, but hadn't reached a solution yet.

**Comment by pdxfixit** [comment]
I just forced master back to b1ebe9e.

**Comment by pdxfixit** [comment]
When I cherrypicked db9c342 and committed it to b1ebe9e, I got the following errors;

```
bigip/resource_bigip_ltm_irule.go:20: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_monitor.go:21: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_node.go:21: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_policy.go:25: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_pool.go:23: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_virtual_address.go:20: unknown schema.Resource field 'Importer' in struct literal
bigip/resource_bigip_ltm_virtual_server.go:22: unknown schema.Resource field 'Importer' in struct literal
```

This is where I was looking last; why this error was happening.

**Comment by pdxfixit** [comment]
I've pushed that branch to #35.
Let's do our work there, and once it passes, we can merge it into master.

**Pull request merged**
