### PR TITLE
Update to latest version of go-bigip

### LINKED ISSUE #43: Import latest version of the go-bigip library into project
Some recent updates to the go-bigip library added features I'm looking to utilize in my environment (support for setting VS SSL Profiles, VLANs, and SNATPools). 

I attempted to import the latest go-bigip library from https://github.com/scottdware/go-bigip into the terraform-provider-bigip project I setup locally but got these errors when trying to compile the source code:

image

Looks like some of the functions in go-bigip were updated since it was imported last ( ~10 months ago) and the calls in the provider-bigip code need to be updated to support these changes. Would it be possible to resolve these conflicts and pull the latest version of the go-bigip library into this project?

### PR DESCRIPTION
**Pull request by jakauppila**
Updates scottdware/go-bigip to the latest version and addresses a few changes implemented in the library.

This PR (https://github.com/scottdware/go-bigip/pull/20) added a ConfigOptions to NewSession and NewTokenSession; as of now there's just one defaulted value, so I figure that can be added to the schema here at a later date.

This commit https://github.com/scottdware/go-bigip/commit/7991c71f16ee28a084c8b7223bb0323d256f81cb changes PoolMembers to return a struct containing a pool members name and state rather than just the name, so added some additional logic to account for that.

All acceptance tests are passing for me with the code changes. With these updates in place we can start adding additional functionality.

Fixes #43

### CODE REVIEW

**Comment by jakauppila** [comment]
Looking through the other issues, this addresses #39 as well.

**Comment by aburnett** [comment]
Thanks for the help. If you can get the build passing I'll merge it in.

**Comment by jakauppila** [comment]
@aburnett Can a Travis build be kicked off against the current master? I would like to see if upstream changes broke the build as it appears that it's pulling the latest version of Terraform; I'd do it against my own but I can't login to Travis due to https://github.com/travis-ci/travis-ci/issues/7612.

**Comment by jakauppila** [comment]
I had submitted #45 just to verify, it appears that upstream Terraform changes broke the build.

How do we want to deal with that? Pulling down Terraform itself isn't required to build the provider, is it? If that's the case, we should be able to remove that from .travis.yml.

**Comment by jakauppila** [comment]
@aburnett Reworked the makefile and .travis.yml to get the build working again; it didn't look like a bit of the content was needed. It's still building fine locally and on Travis.

**Comment by aburnett** [comment]
@pdxfixit looks like you were the one to add that stuff in the Makefile. Do you see any reason why it still needs to be in there?

**Comment by pdxfixit** [comment]
IIRC, I was having trouble getting the plugin to compile correctly. Seemed a bit hacky to do it the way I did, but I didn't know a better way.

If tests are passing, I see no reason for it to remain.

**Comment by aburnett** [comment]
So, apparently I no longer have write access to this repo so I can't merge the PR. =(

**Pull request merged**
